### ISSUE TITLE
Drag inside panel in slide mode

### ISSUE THREAD

**Issue by viktoriiakrause** [YvesCoding/vuescroll#103]
I'd like to know if there is any way to drag anything inside panel, when slide mode is enabled.
[codesandbox](https://codesandbox.io/s/v330wz4nny) (to try drag handle switch vuescroll to native mode in scrollOptions in App.vue file).

**Comment by wangyi7099** [comment]
Because `smooth-dnd` adds `mousedown` event on `document`.

https://github.com/kutlugsahin/smooth-dnd/blob/3a3b66a70643603a566c5a21f9b989db89fe4f62/src/mediator.js#L37

And vuescroll adds `mousedown` on `div` and calls `stopPropagation `.
https://github.com/YvesCoding/vuescroll/blob/1c9f2e65bfe6cfd4e588ddafb86fbe18080de3b8/src/core/third-party/scroller/listener.js#L26

**Comment by viktoriiakrause** [comment]
Thanks for your reply!
I see the thing now, is there a possibility to implement a new feature which will include such functionality?

**Comment by wangyi7099** [comment]
Does `vue-smooth-dnd` have drag-start and drag-end hooks ? If so, I'd like to add an option to `disable/enable` scrolling on slide mode.

**Comment by viktoriiakrause** [comment]
Yes, `vue-smooth-dnd` has such events, but the thing is, that they are not firing within slide mode. The only way I could get to event was putting `mousedown` to `.drag-handle` (I updated [codesandbox](https://codesandbox.io/s/v330wz4nny))

**Comment by wangyi7099** [comment]
OK. I will add an option for scroller, to `disable/enable` scrolling  in next release. You can disable scrolling in `dragHandleMousedown` and enable in `onDragEnd`.

**Comment by wangyi7099** [comment]
Close it now due to I have added an option called disable for scroller in 4.11.0 version.
