### ISSUE TITLE
Bug: mouse with horizontal scroll wheel scrolls vertically

### ISSUE THREAD

**Issue by jonagoldman** [YvesCoding/vuescroll#197]
On a mouse that have both vertical and horizontal scroll wheels, using the **horizontal** scroll wheel triggers a vertical scroll instead of an horizontal scroll.

![Screenshot from 2020-04-12 19-27-28](https://user-images.githubusercontent.com/1297559/79083400-ad067480-7cf3-11ea-964c-b7051694e659.png)

**Comment by wangyi7099** [comment]
Interesting. Haven't used this kind of mouse. I will have a look into this by googling or stackoverflow.

**Comment by jonagoldman** [comment]
Great! In case it helps I have also tested [simplebar](https://github.com/Grsmto/simplebar) and it is working correctly there.

**Comment by wangyi7099** [comment]
Vuescroll had used this kind of way like simplebar or something else similar scrollbar to scroll before. But since we received a feature : [Horizontal scroll by mousewheel ](https://github.com/YvesCoding/vuescroll/issues/156) , we changed the way to scroll, we have to judge the [scroll position by ourselves](https://github.com/YvesCoding/vuescroll/blob/48c5895387dd5d410fbd13999ff23d02b60fb932/src/mode/native/mixins/update-native.js#L66) rather than browser. So we may have lost some judgement conditions of the mouse  like yours.

**Comment by zyphermann** [comment]
Can confirm this is a bug. On MacOS horizontal scrolling with 2 fingers does not work. It scrolls vertically instead.

**Comment by wangyi7099** [comment]
> Can confirm this is a bug. On MacOS horizontal scrolling with 2 fingers does not work. It scrolls vertically instead.

Which version are you usning?  Can you elaborate?

**Comment by wangyi7099** [comment]
Maybe there are still some logic errors in this code block
https://github.com/YvesCoding/vuescroll/blob/760968270dd934c2f6550a98e41810fa438cfd8f/src/mode/native/mixins/update-native.js#L67

**Comment by wangyi7099** [comment]
Try `4.16.3`  and you can see `locking` to false to enable two directions scrolling.
```
ops: {
vuescroll: {
 locking : false
}
}

```
